packages:
  - apps/*
  - packages/*
  - configs/*

catalogs:
  react19:
    '@biomejs/biome': 2.1.3
    '@tailwindcss/postcss': 4.1.8
    '@tanstack/react-form': 1.12.1
    '@tanstack/react-query': 5.80.2
    '@tanstack/react-table': 8.21.3
    '@types/node': 22.13.14
    '@types/react': 19.1.7
    '@types/react-dom': 19.1.7
    '@wagmi/cli': 2.3.1
    "next": 15.4.5
    "postcss": 8.5.4
    "react": 19.1.1
    "react-dom": 19.1.1
    "tailwindcss": 4.1.8
    "turbo": 2.5.5
    "typescript": 5.8.3
    "viem": 2.37.3
    "wagmi": 2.16.9
    "zod": 4.0.13
    "porto": 0.2.10
    "ox": 0.8.6
    "zustand": 5.0.7

